# Generated by Django 2.1 on 2018-08-11 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Índice')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice',
                'verbose_name_plural': 'Índices',
            },
        ),
        migrations.CreateModel(
            name='IndexItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual')),
                ('period_from', models.DateTimeField(blank=True, null=True, verbose_name='Período inicial')),
                ('period_until', models.DateTimeField(blank=True, null=True, verbose_name='Período Final')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.Index', verbose_name='Índice')),
            ],
            options={
                'verbose_name': 'Índice Mensal',
                'verbose_name_plural': 'Índices Mensais',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aporte inicial')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tributação')),
                ('broker', models.CharField(blank=True, max_length=100, null=True, verbose_name='Corretora')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Aluguel')),
                ('dividends', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dividendos')),
                ('date_initial_amount', models.DateTimeField(verbose_name='Data do aporte')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('representativeness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Representatividade')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('equity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Equity', verbose_name='Patrimônio')),
                ('index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Index', verbose_name='Índice')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Natureza')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Natureza',
                'verbose_name_plural': 'Naturezas',
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Nature', verbose_name='Natureza'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
