# Generated by Django 2.1 on 2018-08-05 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=100)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('broker', models.CharField(max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dividends', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_initial_amount', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('representativeness', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Equity')),
            ],
        ),
        migrations.CreateModel(
            name='Profitable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ipca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cdi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selic', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period_from', models.DateTimeField()),
                ('period_until', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Profitable'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
