# Generated by Django 2.1 on 2018-08-05 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('nature', models.CharField(max_length=100, verbose_name='Natureza')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aporte inicial')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tributação')),
                ('broker', models.CharField(blank=True, max_length=100, null=True, verbose_name='Corretora')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Aluguel')),
                ('dividends', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dividendos')),
                ('date_initial_amount', models.DateTimeField(verbose_name='Data do aporte')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('representativeness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Representatividade')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('equity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Equity', verbose_name='Patrimônio')),
            ],
        ),
        migrations.CreateModel(
            name='Profitable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('ipca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IPCA')),
                ('cdi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CDI')),
                ('selic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SELIC')),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa fixa')),
                ('period_from', models.DateTimeField(blank=True, null=True, verbose_name='Período inicial')),
                ('period_until', models.DateTimeField(blank=True, null=True, verbose_name='Período Final')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.Profitable', verbose_name='Rentabilidade'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
